/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AllBlogsRouteImport } from './routes/all-blogs'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppCallerRouteImport } from './routes/app.caller'
import { Route as AppChatRouteImport } from './routes/app.chat'
import { Route as AppConversationsRouteImport } from './routes/app.conversations'
import { Route as AppEmailRouteImport } from './routes/app.email'
import { Route as AppMessagesRouteImport } from './routes/app.messages'
import { Route as AppStudioRouteImport } from './routes/app.studio'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as IndustriesEducationRouteImport } from './routes/industries.education'
import { Route as IndustriesRealEstateRouteImport } from './routes/industries.real-estate'
import { Route as AppLeadsIndexRouteImport } from './routes/app.leads.index'
import { Route as AppLeadsLeadIdRouteImport } from './routes/app.leads.$leadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AllBlogsRoute = AllBlogsRouteImport.update({
  id: '/all-blogs',
  path: '/all-blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCallerRoute = AppCallerRouteImport.update({
  id: '/caller',
  path: '/caller',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppConversationsRoute = AppConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailRoute = AppEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AppRoute,
} as any)
const AppMessagesRoute = AppMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AppRoute,
} as any)
const AppStudioRoute = AppStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AppRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesEducationRoute = IndustriesEducationRouteImport.update({
  id: '/industries/education',
  path: '/industries/education',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRealEstateRoute = IndustriesRealEstateRouteImport.update({
  id: '/industries/real-estate',
  path: '/industries/real-estate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLeadsIndexRoute = AppLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsLeadIdRoute = AppLeadsLeadIdRouteImport.update({
  id: '/leads/$leadId',
  path: '/leads/$leadId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/all-blogs': typeof AllBlogsRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/marketing': typeof MarketingRoute
  '/pricing': typeof PricingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/caller': typeof AppCallerRoute
  '/app/chat': typeof AppChatRoute
  '/app/conversations': typeof AppConversationsRoute
  '/app/email': typeof AppEmailRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/studio': typeof AppStudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/app/': typeof AppIndexRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/all-blogs': typeof AllBlogsRoute
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/marketing': typeof MarketingRoute
  '/pricing': typeof PricingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/caller': typeof AppCallerRoute
  '/app/chat': typeof AppChatRoute
  '/app/conversations': typeof AppConversationsRoute
  '/app/email': typeof AppEmailRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/studio': typeof AppStudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/app': typeof AppIndexRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads': typeof AppLeadsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/all-blogs': typeof AllBlogsRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/blogs': typeof BlogsRoute
  '/marketing': typeof MarketingRoute
  '/pricing': typeof PricingRoute
  '/app/admin': typeof AppAdminRoute
  '/app/caller': typeof AppCallerRoute
  '/app/chat': typeof AppChatRoute
  '/app/conversations': typeof AppConversationsRoute
  '/app/email': typeof AppEmailRoute
  '/app/messages': typeof AppMessagesRoute
  '/app/studio': typeof AppStudioRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/education': typeof IndustriesEducationRoute
  '/industries/real-estate': typeof IndustriesRealEstateRoute
  '/app/': typeof AppIndexRoute
  '/app/leads/$leadId': typeof AppLeadsLeadIdRoute
  '/app/leads/': typeof AppLeadsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/all-blogs'
    | '/app'
    | '/auth'
    | '/blogs'
    | '/marketing'
    | '/pricing'
    | '/app/admin'
    | '/app/caller'
    | '/app/chat'
    | '/app/conversations'
    | '/app/email'
    | '/app/messages'
    | '/app/studio'
    | '/blog/$slug'
    | '/industries/education'
    | '/industries/real-estate'
    | '/app/'
    | '/app/leads/$leadId'
    | '/app/leads/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/all-blogs'
    | '/auth'
    | '/blogs'
    | '/marketing'
    | '/pricing'
    | '/app/admin'
    | '/app/caller'
    | '/app/chat'
    | '/app/conversations'
    | '/app/email'
    | '/app/messages'
    | '/app/studio'
    | '/blog/$slug'
    | '/industries/education'
    | '/industries/real-estate'
    | '/app'
    | '/app/leads/$leadId'
    | '/app/leads'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/all-blogs'
    | '/app'
    | '/auth'
    | '/blogs'
    | '/marketing'
    | '/pricing'
    | '/app/admin'
    | '/app/caller'
    | '/app/chat'
    | '/app/conversations'
    | '/app/email'
    | '/app/messages'
    | '/app/studio'
    | '/blog/$slug'
    | '/industries/education'
    | '/industries/real-estate'
    | '/app/'
    | '/app/leads/$leadId'
    | '/app/leads/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AllBlogsRoute: typeof AllBlogsRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogsRoute: typeof BlogsRoute
  MarketingRoute: typeof MarketingRoute
  PricingRoute: typeof PricingRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesEducationRoute: typeof IndustriesEducationRoute
  IndustriesRealEstateRoute: typeof IndustriesRealEstateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/all-blogs': {
      id: '/all-blogs'
      path: '/all-blogs'
      fullPath: '/all-blogs'
      preLoaderRoute: typeof AllBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/caller': {
      id: '/app/caller'
      path: '/caller'
      fullPath: '/app/caller'
      preLoaderRoute: typeof AppCallerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conversations': {
      id: '/app/conversations'
      path: '/conversations'
      fullPath: '/app/conversations'
      preLoaderRoute: typeof AppConversationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/email': {
      id: '/app/email'
      path: '/email'
      fullPath: '/app/email'
      preLoaderRoute: typeof AppEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/messages': {
      id: '/app/messages'
      path: '/messages'
      fullPath: '/app/messages'
      preLoaderRoute: typeof AppMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/studio': {
      id: '/app/studio'
      path: '/studio'
      fullPath: '/app/studio'
      preLoaderRoute: typeof AppStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/education': {
      id: '/industries/education'
      path: '/industries/education'
      fullPath: '/industries/education'
      preLoaderRoute: typeof IndustriesEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/real-estate': {
      id: '/industries/real-estate'
      path: '/industries/real-estate'
      fullPath: '/industries/real-estate'
      preLoaderRoute: typeof IndustriesRealEstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/leads/': {
      id: '/app/leads/'
      path: '/leads'
      fullPath: '/app/leads/'
      preLoaderRoute: typeof AppLeadsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/leads/$leadId': {
      id: '/app/leads/$leadId'
      path: '/leads/$leadId'
      fullPath: '/app/leads/$leadId'
      preLoaderRoute: typeof AppLeadsLeadIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppCallerRoute: typeof AppCallerRoute
  AppChatRoute: typeof AppChatRoute
  AppConversationsRoute: typeof AppConversationsRoute
  AppEmailRoute: typeof AppEmailRoute
  AppMessagesRoute: typeof AppMessagesRoute
  AppStudioRoute: typeof AppStudioRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLeadsLeadIdRoute: typeof AppLeadsLeadIdRoute
  AppLeadsIndexRoute: typeof AppLeadsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppCallerRoute: AppCallerRoute,
  AppChatRoute: AppChatRoute,
  AppConversationsRoute: AppConversationsRoute,
  AppEmailRoute: AppEmailRoute,
  AppMessagesRoute: AppMessagesRoute,
  AppStudioRoute: AppStudioRoute,
  AppIndexRoute: AppIndexRoute,
  AppLeadsLeadIdRoute: AppLeadsLeadIdRoute,
  AppLeadsIndexRoute: AppLeadsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AllBlogsRoute: AllBlogsRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogsRoute: BlogsRoute,
  MarketingRoute: MarketingRoute,
  PricingRoute: PricingRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesEducationRoute: IndustriesEducationRoute,
  IndustriesRealEstateRoute: IndustriesRealEstateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
